name: Build

on: [push]

defaults:
  run:
    shell: bash
    working-directory: src

jobs:
  Build:
    name: Build release binaries

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller pytest
          pip install -r requirements.txt

      - name: Build with pyinstaller
        run: pyinstaller --onefile --name=app-${{ matrix.os }} main.py

      - name: Deploy artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}
          path: app/dist/app-${{ matrix.os }}*
          if-no-files-found: error